name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'
      - 'deps'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'docs'
      - 'documentation'
      - 'dependencies'
      - 'deps'
      - 'chore'
      - 'maintenance'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Installation

  ### Homebrew (macOS and Linux)
  ```bash
  brew tap lakshyajain-0291/gitcury
  brew install gitcury
  ```

  ### Scoop (Windows)
  ```bash
  scoop bucket add gitcury https://github.com/lakshyajain-0291/gitcury-Scoop-Bucket.git
  scoop install gitcury
  ```

  ### Docker
  ```bash
  docker pull lakshyajain1503/gitcury:latest
  ```

  ### Direct Download
  Binary packages for different platforms are available below.
