# GoReleaser configuration file
project_name: gitcury
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: gitcury
    main: ./main.go
    binary: gitcury
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    # Add mod timestamp for reproducible builds
    mod_timestamp: '{{ .CommitTimestamp }}'
    # Ensure the binary is not marked as development version
    flags:
      - -trimpath

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - config.json.example
    # Allow files with different permissions
    rlcp: true
  - id: windows-zip
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - config.json.example

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'merge conflict'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: lakshyajain-0291
    name: GitCury
  prerelease: auto

# Homebrew Tap configuration
brews:
  - name: gitcury
    tap:
      owner: lakshyajain-0291
      name: homebrew-gitcury
      token: "{{ .Env.HOMEBREW_TAP_PAT }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/lakshyajain-0291/GitCury"
    description: "AI-Powered Git Automation CLI tool"
    license: "MIT"
    test: |
      system "#{bin}/gitcury --version"

# Scoop Bucket configuration
scoops:
  - name: gitcury
    bucket:
      owner: lakshyajain-0291
      name: GitCury-Scoop-Bucket
      token: "{{ .Env.SCOOP_BUCKET_PAT }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/lakshyajain-0291/GitCury"
    description: "AI-Powered Git Automation CLI tool"
    license: "MIT"

# Docker images
dockers:
  - image_templates:
      - "lakshyajain0291/gitcury:latest"
      - "lakshyajain0291/gitcury:{{ .Tag }}"
      - "lakshyajain0291/gitcury:v{{ .Major }}"
      - "lakshyajain0291/gitcury:v{{ .Major }}.{{ .Minor }}"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
