version: 2
project_name: gitcury
before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: gitcury
    main: ./main.go
    binary: gitcury
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - config.json.example
      
snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'merge conflict'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: lakshyajain-0291
    name: gitcury
  prerelease: auto

brews:
  - name: gitcury
    repository:
      owner: lakshyajain-0291
      name: homebrew-gitcury
      token: "{{ .Env.HOMEBREW_TAP_PAT }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/lakshyajain-0291/gitcury"
    description: "AI-Powered Git Automation CLI tool"
    license: "MIT"
    test: |
      system "#{bin}/gitcury --version"

scoops:
  - name: gitcury
    repository:
      owner: lakshyajain-0291
      name: gitcury-scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_PAT }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/lakshyajain-0291/gitcury"
    description: "AI-Powered Git Automation CLI tool"
    license: "MIT"

dockers:
  - image_templates:
      - "lakshyajain1503/gitcury:latest"
      - "lakshyajain1503/gitcury:{{ .Tag }}"
      - "lakshyajain1503/gitcury:v{{ .Major }}"
      - "lakshyajain1503/gitcury:v{{ .Major }}.{{ .Minor }}"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
