name: Fast Checks

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  quick-check:
    name: Quick Build and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: go.sum

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet ./...

      - name: Quick lint (essential checks only)
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --fast --timeout=1m --disable-all --enable=errcheck,gosimple,govet,ineffassign,staticcheck,typecheck,unused
          skip-cache: false
          skip-pkg-cache: false
          skip-build-cache: false
