name: Release GitCury

on:
  push:
    tags:
      - 'v*' # Triggers the workflow when a tag like v0.1.0, v1.2.3 is pushed

permissions:
  contents: write # Needed to create releases and upload assets
  packages: write # Needed to publish Docker images to GitHub Packages

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # GoReleaser needs the full git history to generate changelogs

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Use your project's Go version

      # Login to Docker Hub
      - name: Log in to Docker Hub
        if: success() # Only run if previous steps succeed
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Store as an encrypted secret in GitHub

      # QEMU setup for multi-arch Docker builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Buildx setup for multi-arch Docker builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5 # Use the latest version
        with:
          version: latest
          args: release --clean # '--clean' removes the dist folder before building
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
          # For Homebrew Tap updates
          HOMEBREW_TAP_PAT: ${{ secrets.HOMEBREW_TAP_PAT }}
          # For Scoop Bucket updates
          SCOOP_BUCKET_PAT: ${{ secrets.SCOOP_BUCKET_PAT }}
          # Docker Hub credentials are passed from the docker/login-action
